//Localized words for Schedule
ej.Schedule.Locale["ar-AE"] = {
    ReminderWindowTitle: "نافذة تذكير",
    CreateAppointmentTitle: "إنشاء التعيين",
    RecurrenceEditTitle: "تحرير كرر تعيين",
    RecurrenceEditMessage: "كيف تريد أن تغيير المواعيد في سلسلة الأحداث؟",
    RecurrenceEditOnly: "فقط هذا التعيين",
    RecurrenceEditSeries: "سلسلة كاملة",
    PreviousAppointment: "تعيين السابق",
    NextAppointment: "تعيين المقبل",
    AppointmentSubject: "موضوع",
    StartTime: "وقت البدء",
    EndTime: "نهاية الوقت",
    AllDay: "طوال اليوم",
    StartTimeZone: "بدء والوقت",
    EndTimeZone: "نهاية والوقت",
    Today: "اليوم",
    Recurrence: "تكرر",
    Done: "فعله",
    Cancel: "إلغاء",
    Ok: "حسنا",
    RepeatBy: "كرر بواسطة",
    RepeatEvery: "كرر كل",
    RepeatOn: "كرر على",
    StartsOn: "يبدأ يوم",
    Ends: "ينتهي",
    Summary: "ملخص",
    Daily: "يوميا",
    Weekly: "أسبوعيا",
    Monthly: "شهريا",
    Yearly: "سنويا",
    Every: "كل",
    EveryWeekDay: "كل ايام الاسبوع",
    Never: "أبدا",
    After: "بعد",
    Occurence: "الأحداث",
    On: "على",
    Edit: "تحرير",
    RecurrenceDay: "أيام",
    RecurrenceWeek: "أسابيع",
    RecurrenceMonth: "أشهر",
    RecurrenceYear: "سنوات",
    The: "ال",
    OfEvery: "كل",
    First: "أولا",
    Second: "ثان",
    Third: "ثالث",
    Fourth: "رابع",
    Last: "مشاركة",
    WeekDay: "يوم من أيام الأسبوع",
    WeekEndDay: "اليوم نهاية الاسبوع",
    Subject: "موضوع",
    Categorize: "الفئات",
    DueIn: "في المقرر",
    DismissAll: "افصل الكل",
    Dismiss: "رفض",
    OpenItem: "فتح البند",
    Snooze: "غفوة",
    Day: "يوم",
    Week: "أسبوع",
    WorkWeek: "أسبوع العمل",
    Month: "شهر",
    AddEvent: "إضافة حدث",
    CustomView: "عرض مخصص",
    Agenda: "جدول أعمال",
    Detailed: "مفصل",
    EventBeginsin: "تعيين يبدأ في",
    Editevent: "تحرير تعيين",
    Editseries: "تحرير السلسلة",
    Times: "مرات",
    Until: "حتى",
    Eventwas: "كان التعيين",
    Hours: "ساعة",
    Minutes: "دقائق",
    Overdue: "تعيين طال",
    Days: "يوم",
    Event: "حالة",
    Select: "حدد",
    Previous: "السابق",
    Next: "التالى",
    Close: "غلق",
    Delete: "حذف",
    Date: "تاريخ",
    Showin: "تظهر في",
    Gotodate: "إذهب إلى تاريخ",
    Resources: "الموارد",
    RecurrenceDeleteTitle: "حذف كرر تعيين",
    Location: "موقع",
    Priority: "أفضلية",
    RecurrenceAlert: "إنذار",
    NoTitle: "بدون عنوان",
    WrongPattern: "نمط التكرار غير صالح",
    CreateError: "يجب أن تكون مدة التعيين أقصر من مدى تكرار حدوثه. تقصير المدة، أو تغيير نمط التكرار في مربع الحوار تعيين تكرار.",
    DragResizeError: "لا يمكن إعادة جدولة حدوث الموعد المتكرر إذا تخطى تكرار لاحق من نفس التعيين.",
    MouseOverDeleteTitle: "حذف موعد",
    DeleteConfirmation: "هل أنت متأكد أنك تريد حذف هذا التعيين؟",
    Time: "مرة",
    StartTimeZone: "بداية منطقة زمنية",
    EndTimeZone: "النهاية منطقة زمنية",
    NoTitle: "بدون عنوان",
    OverFlowAppCount: "المزيد من التعيينات (ق )",
    AppointmentIndicator: "انقر إلى أكثر تعيينات",
    EmptyResultText: "لا اقتراحات",
	BlockIntervalAlertTitle: "محزر",
    BlockIntervalError: "تم حظر الفاصل الزمني المحدد وغير متاح للاختيار.",
    RecurrenceDateValidation: "بعض الشهور أقل من التواريخ المحددة. وخلال هذه الأشهر، سيحدث الوقوع في آخر تاريخ من الشهر",
    SeriesChangeAlert: "سيتم إلغاء التغييرات التي تم إجراؤها على حالات معينة من هذه السلسلة وتتوافق هذه التعيينات مع السلسلة مرة أخرى."
};

ej.Schedule.Locale["fr-FR"] = {
    ReminderWindowTitle: "Fenêtre de rappel",
    CreateAppointmentTitle: "créer un rendez-",
    RecurrenceEditTitle: "Modifier répétition nomination",
    RecurrenceEditMessage: "Comment voulez-vous changer le cas dans la série?",
    RecurrenceEditOnly: "Seulement cette nomination",
    RecurrenceEditSeries: "La série entière",
    PreviousAppointment: "Nomination précédente",
    NextAppointment: "prochain rendez-vous",
    AppointmentSubject: "sujet",
    StartTime: "Heure de début",
    EndTime: "Heure de fin",
    AllDay: "toute la journée",
    Today: "aujourd'hui",
    Recurrence: "répétition",
    Done: "Terminé",
    Cancel: "annuler",
    Ok: "Ok",
    RepeatBy: "Répétez par",
    RepeatEvery: "répéter chaque",
    RepeatOn: "répéter l'opération sur",
    StartsOn: "démarre sur",
    Ends: "extrémités",
    Summary: "résumé",
    Daily: "quotidien",
    Weekly: "hebdomadaire",
    Monthly: "mensuel",
    Yearly: "annuel",
    Every: "tous",
    EveryWeekDay: "chaque jour de la semaine",
    Never: "jamais",
    After: "après",
    Occurrence: "apparition",
    On: "sur",
    Edit: "Modifier",
    RecurrenceDay: "Jour (s)",
    RecurrenceWeek: "Semaine (s)",
    RecurrenceMonth: "Mois (s)",
    RecurrenceYear: "Année (s)",
    The: "la",
    OfEvery: "de chaque",
    First: "première",
    Second: "deuxième",
    Third: "troisième",
    Fourth: "quatrième",
    Last: "dernier",
    WeekDay: "jour de la semaine",
    WeekEndDay: "Jour de week-end",
    Subject: "sujet",
    Categorize: "Catégories",
    DueIn: "En raison",
    DismissAll: "rejeter tout",
    Dismiss: "rejeter",
    OpenItem: "Ouvrir l'élément",
    Snooze: "répétition",
    Day: "jour",
    Week: "semaine",
    WorkWeek: "Semaine de travail",
    Month: "mois",
    AddEvent: "Ajouter événement",
    CustomView: "Vue personnalisée",
    Agenda: "ordre du jour",
    Detailed: "détaillé",
    EventBeginsin: "Nomination commence dans",
    Editevent: "Modifier nomination",
    Editseries: "Modifier série",
    Times: "fois",
    Until: "jusqu'à",
    Eventwas: "rendez-vous était",
    Hours: "hrs",
    Minutes: "minutes",
    Overdue: "en retard",
    Days: "jour (s)",
    Event: "Sujet",
    Select: "sélectionner",
    Previous: "prev",
    Next: "suivant",
    Close: "proche",
    Delete: "effacer",
    Date: "date",
    Showin: "montrer en",
    Gotodate: "Aller à la date",
    Resources: "RESSOURCES",
    RecurrenceDeleteTitle: "Supprimer répétition rendez-",
    Location: "emplacement",
    Priority: "priorité",
    RecurrenceAlert: "alerte",
    WrongPattern: "Le modèle de récurrence est pas valable",
    CreateError: "La durée de la nomination doit être plus courte que la façon dont elle se produit fréquemment. Raccourcir la durée ou changer le modèle de récurrence dans la boîte de dialogue Récurrence de rendez.",
    DragResizeError: "Impossible de replanifier une occurrence du rendez-vous récurrent. si elle saute sur une occurrence ultérieure du même rendez-vous.",
    StartEndError: "L'heure de fin doit être supérieur à l'heure de début",
    MouseOverDeleteTitle: "supprimer un rendez-",
    DeleteConfirmation: "Êtes-vous sûr de vouloir supprimer ce rendez-vous?",
    Time: "Temps",
    StartTimeZone: "Commencez TimeZone",
    EndTimeZone: "TimeZone Fin",
    NoTitle: "Pas de titre",
    OverFlowAppCount: "plus rendez-vous (s)",
    AppointmentIndicator: "Cliquez pour plus de rendez-vous",
    EmptyResultText: "Pas de suggestions",
	BlockIntervalAlertTitle: "Alerte",
    BlockIntervalError: "L'intervalle de temps choisi a été bloqué et est indisponible pour la sélection.",
    RecurrenceDateValidation: "Certains mois ont moins de dates sélectionnées. Pour ces mois, l'occurrence tombera à la dernière date du mois",
    SeriesChangeAlert: "Les modifications apportées aux instances spécifiques de cette série seront annulées et ces rendez-vous seront identiques à la série"
};

ej.Schedule.Locale["vi-VN"] = {
    ReminderWindowTitle: "cửa sổ nhắc nhở",
    CreateAppointmentTitle: "tạo bổ nhiệm",
    RecurrenceEditTitle: "Chỉnh sửa bổ nhiệm lại",
    RecurrenceEditMessage: "Làm thế nào bạn muốn thay đổi các sự kiện trong chuỗi?",
    RecurrenceEditOnly: "Chỉ bổ nhiệm này",
    RecurrenceEditSeries: "toàn bộ loạt",
    PreviousAppointment: "Bổ nhiệm trước",
    NextAppointment: "Bổ nhiệm tiếp theo",
    AppointmentSubject: "Tiêu đề",
    StartTime: "Thời gian bắt đầu",
    EndTime: "Thời gian kết thúc",
    AllDay: "mọi ngày",
    Today: "hôm nay",
    Recurrence: "lặp lại",
    Done: "làm xong",
    Cancel: "hủy bỏ",
    Ok: "Được",
    RepeatBy: "lặp lại bởi",
    RepeatEvery: "lặp lại mỗi",
    RepeatOn: "lặp lại",
    StartsOn: "bắt đầu từ ngày",
    Ends: "đầu",
    Summary: "Tóm tắt",
    Daily: "hàng ngày",
    Weekly: "hàng tuần",
    Monthly: "hàng tháng",
    Yearly: "hàng năm",
    Every: "mỗi",
    EveryWeekDay: "mỗi ngày trong tuần",
    Never: "không bao giờ",
    After: "sau khi",
    Occurrence: "sự xuất hiện",
    On: "trên",
    Edit: "chỉnh sửa",
    RecurrenceDay: "Ngày (s)",
    RecurrenceWeek: "Tuần (s)",
    RecurrenceMonth: "Tháng (s)",
    RecurrenceYear: "Năm (s)",
    The: "các",
    OfEvery: "của mỗi",
    First: "đầu tiên",
    Second: "thứ hai",
    Third: "thứ ba",
    Fourth: "thứ tư",
    Last: "cuối cùng",
    WeekDay: "các ngày trong tuần",
    WeekEndDay: "Ngày cuối tuần",
    Subject: "Tiêu đề",
    Categorize: "Thể loại",
    DueIn: "Trong do",
    DismissAll: "Tất cả bỏ",
    Dismiss: "miễn nhiệm",
    OpenItem: "mở hàng",
    Snooze: "giấc ngu ngắn",
    Day: "ngày",
    Week: "tuần",
    WorkWeek: "Tuần làm việc",
    Month: "tháng",
    AddEvent: "Thêm sự kiện",
    CustomView: "tuỳ chỉnh view",
    Agenda: "chương trình nghị sự",
    Detailed: "chi tiết",
    EventBeginsin: "Bắt đầu hẹn trong",
    Editevent: "chỉnh sửa bổ nhiệm",
    Editseries: "chỉnh sửa hàng loạt",
    Times: "lần",
    Until: "đến",
    Eventwas: "được bổ nhiệm",
    Hours: "hrs",
    Minutes: "phút",
    Overdue: "quá hạn",
    Days: "ngày(s)",
    Event: "Chủ đề",
    Select: "chọn",
    Previous: "trước",
    Next: "tiếp theo",
    Close: "gần",
    Delete: "xóa",
    Date: "ngày",
    Showin: "Hiện tại",
    Gotodate: "Chuyển Đến ngày",
    Resources: "TÀI NGUYÊN",
    RecurrenceDeleteTitle: "Xóa cuộc hẹn lặp lại",
    Location: "vị trí",
    Priority: "quyền ưu tiên",
    RecurrenceAlert: "báo động",
    WrongPattern: "Các mô hình lặp lại chưa hợp lệ",
    CreateError: "Thời hạn bổ nhiệm phải ngắn hơn thường xuyên như thế nào nó xảy ra. Rút ngắn thời gian, hoặc thay đổi mô hình tái phát trong Appointment Recurrence hộp thoại.",
    DragResizeError: "Không thể sắp xếp lại một sự xuất hiện của các cuộc hẹn định kỳ. nếu nó bỏ qua một sự xuất hiện muộn của cuộc hẹn cùng.",
    StartEndError: "Kết thúc thời gian nên lớn hơn so với thời gian bắt đầu",
    MouseOverDeleteTitle: "xóa cuộc hẹn",
    DeleteConfirmation: "Bạn có chắc chắn muốn xóa hẹn này ?",
    Time: "thời gian",
    StartTimeZone: "bắt đầu múi giờ",
    EndTimeZone: "múi giờ cuối",
    NoTitle: "Không tiêu đề",
    OverFlowAppCount: "hơn cuộc hẹn",
    AppointmentIndicator: "Nhấn vào cho các cuộc hẹn hơn",
    EmptyResultText: "no hay sugerencias",
	BlockIntervalAlertTitle: "Cảnh báo",
    BlockIntervalError: "Khoảng thời gian đã chọn đã bị chặn và không khả dụng cho lựa chọn",
    RecurrenceDateValidation: "Một số tháng có ít hơn ngày được chọn. Trong những tháng này, sự xuất hiện sẽ rơi vào ngày cuối cùng của tháng",
    SeriesChangeAlert: "Những thay đổi được thực hiện cho các phiên bản cụ thể của loạt bài này sẽ bị hủy bỏ và các cuộc hẹn đó sẽ kết hợp lại loạt bài"
};